#!/usr/bin/env bun
/**
 * Build OpenCode for Android (aarch64)
 *
 * This script:
 * 1. Generates the models-snapshot.js
 * 2. Loads migrations
 * 3. Bundles OpenCode using Bun.build() with compile targeting the host platform
 * 4. Extracts the module graph from the compiled binary
 * 5. Appends it to our Android bun binary to create the final standalone
 */

import { $ } from "bun"
import fs from "fs"
import path from "path"
import { createSolidTransformPlugin } from "@opentui/solid/bun-plugin"

// These are set by the build-opencode.sh wrapper script
const OPENCODE_DIR = process.env.OPENCODE_DIR || (() => { throw new Error("OPENCODE_DIR env var not set") })()
const ANDROID_BUN = process.env.ANDROID_BUN || (() => { throw new Error("ANDROID_BUN env var not set") })()
const ANDROID_OPENTUI = process.env.ANDROID_OPENTUI || (() => { throw new Error("ANDROID_OPENTUI env var not set") })()
const OUTPUT_DIR = process.env.OUTPUT_DIR || (() => { throw new Error("OUTPUT_DIR env var not set") })()

// Validate Android bun exists
if (!fs.existsSync(ANDROID_BUN)) {
  console.error("Android bun binary not found at:", ANDROID_BUN)
  process.exit(1)
}

process.chdir(OPENCODE_DIR)

const VERSION = process.env.OPENCODE_VERSION || "1.18.16"
const CHANNEL = process.env.OPENCODE_CHANNEL || "latest"

console.log(`Building OpenCode v${VERSION} (channel: ${CHANNEL}) for Android aarch64`)

// Step 1: Generate models-snapshot.js
console.log("\n=== Step 1: Generating models-snapshot.js ===")
const modelsUrl = process.env.OPENCODE_MODELS_URL || "https://models.dev"
let modelsData: string = ""
if (process.env.MODELS_DEV_API_JSON) {
  modelsData = await Bun.file(process.env.MODELS_DEV_API_JSON).text()
} else {
  console.log(`Fetching from ${modelsUrl}/api.json ...`)
  let fetchErr: Error | null = null
  for (let attempt = 1; attempt <= 3; attempt++) {
    try {
      const resp = await fetch(`${modelsUrl}/api.json`, { signal: AbortSignal.timeout(15000) })
      if (!resp.ok) throw new Error(`HTTP ${resp.status}`)
      modelsData = await resp.text()
      fetchErr = null
      break
    } catch (err: any) {
      fetchErr = err
      console.error(`  Attempt ${attempt}/3 failed: ${err.message}`)
      if (attempt < 3) await new Promise(r => setTimeout(r, 2000 * attempt))
    }
  }
  if (fetchErr) {
    console.error(`ERROR: Failed to fetch models after 3 attempts: ${fetchErr.message}`)
    process.exit(1)
  }
}
await Bun.write(
  path.join(OPENCODE_DIR, "src/provider/models-snapshot.js"),
  `// @ts-nocheck\n// Auto-generated by build.ts - do not edit\nexport const snapshot = ${modelsData}\n`,
)
await Bun.write(
  path.join(OPENCODE_DIR, "src/provider/models-snapshot.d.ts"),
  `// Auto-generated by build.ts - do not edit\nexport declare const snapshot: Record<string, unknown>\n`,
)
console.log("Generated models-snapshot.js")

// Step 2: Load migrations
console.log("\n=== Step 2: Loading migrations ===")
const migrationDirs = (
  await fs.promises.readdir(path.join(OPENCODE_DIR, "migration"), {
    withFileTypes: true,
  })
)
  .filter((entry) => entry.isDirectory() && /^\d{4}\d{2}\d{2}\d{2}\d{2}\d{2}/.test(entry.name))
  .map((entry) => entry.name)
  .sort()

const migrations = await Promise.all(
  migrationDirs.map(async (name) => {
    const file = path.join(OPENCODE_DIR, "migration", name, "migration.sql")
    const sql = await Bun.file(file).text()
    const match = /^(\d{4})(\d{2})(\d{2})(\d{2})(\d{2})(\d{2})/.exec(name)
    const timestamp = match
      ? Date.UTC(
          Number(match[1]),
          Number(match[2]) - 1,
          Number(match[3]),
          Number(match[4]),
          Number(match[5]),
          Number(match[6]),
        )
      : 0
    return { sql, timestamp, name }
  }),
)
console.log(`Loaded ${migrations.length} migrations`)

// Step 3: Build with Bun.build() --compile for the HOST platform
// This creates a standalone binary for the host, from which we extract the module graph
console.log("\n=== Step 3: Bundling OpenCode ===")

const plugin = createSolidTransformPlugin()

// Find parser.worker.js
const localPath = path.resolve(OPENCODE_DIR, "node_modules/@opentui/core/parser.worker.js")
const rootPath = path.resolve(OPENCODE_DIR, "../../node_modules/@opentui/core/parser.worker.js")
let parserWorkerResolved: string
try {
  parserWorkerResolved = fs.realpathSync(fs.existsSync(localPath) ? localPath : rootPath)
} catch {
  // Try bun's module resolution
  parserWorkerResolved = require.resolve("@opentui/core/parser.worker.js")
}
console.log(`Parser worker: ${parserWorkerResolved}`)

// Android Bun currently does not return a usable `default` value for file-like
// imports transplanted from a host standalone module graph. OpenTUI normally
// performs one such import eagerly for parser.worker.js, which crashes before
// the TUI starts. Make that eager lookup honor OTUI_ASSET_ROOT, just like all
// of OpenTUI's other relocatable runtime assets.
const opentuiCoreDir = path.dirname(parserWorkerResolved)
let assetRootPatchCount = 0
let assetRootReadyCount = 0
for (const name of fs.readdirSync(opentuiCoreDir)) {
  if (!/^chunk-bun-.*\.js$/.test(name)) continue
  const file = path.join(opentuiCoreDir, name)
  const source = fs.readFileSync(file, "utf8")
  const patched = source
    .replaceAll("{ useAssetRoot: false }", "{ useAssetRoot: true }")
    .replaceAll(
      "const root = process.env.OTUI_ASSET_ROOT;",
      "const root = process.env.OTUI_ASSET_ROOT || '/data/data/com.termux/files/usr/libexec/opencode/opentui-assets';",
    )
    .replaceAll(
      "return normalizeLoadedFilePath((await loadBundledFile()).default, metaUrl);",
      "const loadedPath = (await loadBundledFile()).default; if (typeof loadedPath !== 'string') throw new Error(`OpenTUI bundled asset ${key} was not materialized (OTUI_ASSET_ROOT=${process.env.OTUI_ASSET_ROOT ?? ''})`); return normalizeLoadedFilePath(loadedPath, metaUrl);",
    )
  if (patched !== source) {
    fs.writeFileSync(file, patched)
    assetRootPatchCount++
  }
  if (patched.includes("{ useAssetRoot: true }")) assetRootReadyCount++
}
if (assetRootReadyCount === 0) {
  throw new Error("OpenTUI parser worker asset-root patch did not match")
}
console.log(`OpenTUI external Android assets enabled (${assetRootPatchCount} newly patched chunk(s))`)

// v1.18 moved the worker out of cli/cmd/tui into cli/tui.
const workerPath = "./src/cli/tui/worker.ts"

const bunfsRoot = "/$bunfs/root/"
const workerRelativePath = path.relative(OPENCODE_DIR, parserWorkerResolved).replaceAll("\\", "/")

await $`rm -rf ${OUTPUT_DIR}`
await $`mkdir -p ${OUTPUT_DIR}`

// Build with --compile for the HOST platform to get a standalone binary
// We'll extract the module graph from it
const hostBinaryPath = path.join(OUTPUT_DIR, "opencode-host")

console.log("Building standalone binary for host platform...")
const result = await Bun.build({
  conditions: ["browser"],
  tsconfig: "./tsconfig.json",
  plugins: [plugin],
  compile: {
    autoloadBunfig: false,
    autoloadDotenv: false,
    autoloadTsconfig: true,
    autoloadPackageJson: true,
    outfile: hostBinaryPath,
    execArgv: [`--user-agent=opencode/${VERSION}`, "--use-system-ca", "--"],
  },
  entrypoints: ["./src/index.ts", parserWorkerResolved, workerPath],
  define: {
    OPENCODE_VERSION: `'${VERSION}'`,
    OPENCODE_MIGRATIONS: JSON.stringify(migrations),
    OTUI_TREE_SITTER_WORKER_PATH: bunfsRoot + workerRelativePath,
    OPENCODE_WORKER_PATH: workerPath,
    OPENCODE_CHANNEL: `'${CHANNEL}'`,
    OPENCODE_LIBC: "",
  },
})

if (!result.success) {
  console.error("Build failed:")
  for (const msg of result.logs) {
    console.error(msg)
  }
  process.exit(1)
}

console.log(`Host standalone binary: ${hostBinaryPath}`)

// Step 4: Extract module graph from host binary
console.log("\n=== Step 4: Extracting module graph ===")

const hostBinary = await Bun.file(hostBinaryPath).arrayBuffer()
const hostBytes = new Uint8Array(hostBinary)

// Standalone binary format (ELF):
//   [bun binary (seek_pos bytes)]
//   [module_graph bytes]
//   [total_byte_count as u64 LE (8 bytes)]
//
// Module graph internal layout:
//   [string data] [module list] [offsets (32 bytes)] [trailer "\n---- Bun! ----\n" (16 bytes)]
//
// offsets.byte_count = len(string_data) + len(module_list)
// total_byte_count = seek_pos + len(module_graph) + 8 = file_size
//
// We derive the module graph size from the trailer and offsets struct,
// WITHOUT relying on process.execPath (which may differ from the bun
// binary that was embedded during --compile).

const TRAILER_STR = "\n---- Bun! ----\n"
const TRAILER_LEN = TRAILER_STR.length  // 16
const OFFSETS_SIZE_CONST = 32

// Find trailer: it's near the end of the file, just before the final 8-byte u64.
// Search backwards from (end - 8) for the trailer sentinel.
const trailerBuf = Buffer.from(TRAILER_STR)
const searchBuf = Buffer.from(hostBytes.buffer, hostBytes.byteOffset, hostBytes.length)
const trailerEnd = hostBytes.length - 8  // trailer must end here
const expectedTrailerStart = trailerEnd - TRAILER_LEN

// Verify trailer at expected position
const foundTrailer = searchBuf.compare(
  trailerBuf, 0, TRAILER_LEN,
  expectedTrailerStart, trailerEnd
) === 0

if (!foundTrailer) {
  console.error("ERROR: Bun standalone trailer not found at expected position")
  console.error("       The standalone binary format may have changed.")
  process.exit(1)
}

// Read offsets struct (32 bytes) just before the trailer
const offsetsStart = expectedTrailerStart - OFFSETS_SIZE_CONST
const offsetsByteCount = Number(searchBuf.readBigUInt64LE(offsetsStart))

// Module graph total size = byte_count (string data + module list) + offsets(32) + trailer(16)
const moduleGraphSize = offsetsByteCount + OFFSETS_SIZE_CONST + TRAILER_LEN
const hostBunSize = hostBytes.length - 8 - moduleGraphSize

console.log(`Host standalone size: ${hostBytes.length}`)
console.log(`Derived host bun size: ${hostBunSize}`)
console.log(`Module graph size: ${moduleGraphSize}`)

if (hostBunSize <= 0) {
  console.error(`ERROR: Derived host bun size is ${hostBunSize} — something is wrong`)
  process.exit(1)
}

const moduleGraphBytes = hostBytes.slice(hostBunSize, hostBytes.length - 8)
console.log(`Module graph extracted: ${moduleGraphBytes.length} bytes`)
console.log(`Trailer verified: OK`)

// Step 5: Patch the module graph for Android
console.log("\n=== Step 5: Patching module graph for Android ===")

// The module graph format (from StandaloneModuleGraph.zig):
//   [string data: all file names, contents, sourcemaps, bytecodes concatenated]
//   [CompiledModuleGraphFile array]
//   [Offsets struct: 32 bytes]
//   [trailer: "\n---- Bun! ----\n"]
//
// Offsets struct layout (32 bytes, little-endian, unchanged across Bun versions):
//   byte_count:              u64  (8 bytes) - size of everything before the Offsets struct
//   modules_ptr.offset:      u32  (4 bytes)
//   modules_ptr.length:      u32  (4 bytes)
//   entry_point_id:          u32  (4 bytes)
//   compile_exec_argv.offset:u32  (4 bytes)
//   compile_exec_argv.length:u32  (4 bytes)
//   flags:                   u32  (4 bytes)
//
// NOTE: CompiledModuleGraphFile layout varies between Bun versions:
//   - Bun 1.2.x: 36 bytes (4 StringPointers + 3 u8 + 1 padding)
//   - Bun 1.3.x: 52 bytes (6 StringPointers + 4 u8)
// We avoid parsing individual modules. The undici patch is a same-size
// in-place byte replacement in the raw string data, so we don't need to
// know the module struct layout at all. The module list and offsets are
// passed through unchanged.

const mgTrailer = "\n---- Bun! ----\n"
const mgTrailerBuf = Buffer.from(mgTrailer)
const OFFSETS_SIZE = 32

// Parse the module graph — only the Offsets struct (version-independent)
const mgBuf = Buffer.from(moduleGraphBytes)
const trailerPosInMg = mgBuf.lastIndexOf(mgTrailerBuf)
if (trailerPosInMg < 0) throw new Error("Trailer not found in module graph!")

// Offsets struct is just before the trailer
const mgOffsetsStart = trailerPosInMg - OFFSETS_SIZE
const byteCount = Number(mgBuf.readBigUInt64LE(mgOffsetsStart))
const modOff = mgBuf.readUInt32LE(mgOffsetsStart + 8)
const modLen = mgBuf.readUInt32LE(mgOffsetsStart + 12)
const entryId = mgBuf.readUInt32LE(mgOffsetsStart + 16)
const argvOff = mgBuf.readUInt32LE(mgOffsetsStart + 20)
const argvLen = mgBuf.readUInt32LE(mgOffsetsStart + 24)
const flags = mgBuf.readUInt32LE(mgOffsetsStart + 28)

console.log(`Module graph: trailer at ${trailerPosInMg}, offsets at ${mgOffsetsStart}`)
console.log(`byte_count=${byteCount}, modules_ptr=(${modOff},${modLen}), entry_id=${entryId}`)
console.log(`String data region: [0, ${modOff}), Module list: [${modOff}, ${modOff + modLen})`)

// Host Linux Bun emits a bare `undici` global, while Android Bun exposes the
// same built-in namespace as `Undici`. This is independent of graph format and
// remains necessary even when host and target Bun versions match exactly.
const UNDICI_SEARCH  = Buffer.from('__reExport(exports_Undici, undici)')
const UNDICI_REPLACE = Buffer.from('__reExport(exports_Undici, Undici)')
console.log(`\nAndroid patch: Replacing undici->Undici (same size, no offset changes)`)
let undiciPatchCount = 0
let searchPos = 0
const strDataRegion = mgBuf.slice(0, modOff)
while (true) {
  const pos = strDataRegion.indexOf(UNDICI_SEARCH, searchPos)
  if (pos < 0) break
  console.log(`  Found at string data offset ${pos}, replacing...`)
  UNDICI_REPLACE.copy(mgBuf, pos)
  undiciPatchCount++
  searchPos = pos + UNDICI_SEARCH.length
}
if (undiciPatchCount === 0) {
  console.error("WARNING: Android undici reference not found")
} else {
  console.log(`  Patched ${undiciPatchCount} occurrence(s)`)
}

// Since all patches are same-size in-place edits, the module graph is unchanged
// in structure. We just pass through the entire mgBuf (with our in-place edits)
// as the final module graph.
var finalModuleGraph = mgBuf.slice(0, trailerPosInMg + mgTrailerBuf.length)
console.log(`Module graph size: ${finalModuleGraph.length} bytes (unchanged)`)

// Step 6: Create Android standalone binary
console.log("\n=== Step 6: Creating Android standalone binary ===")

const androidBunBytes = new Uint8Array(await Bun.file(ANDROID_BUN).arrayBuffer())
const androidBunSize = androidBunBytes.length
console.log(`Android bun size: ${androidBunSize}`)

// New total_byte_count = android_bun_size + module_graph.length + 8
const newTotalByteCount = androidBunSize + finalModuleGraph.length + 8

// Create the output buffer
const outputSize = androidBunSize + finalModuleGraph.length + 8
const output = new Uint8Array(outputSize)

// Copy Android bun binary
output.set(androidBunBytes, 0)

// Copy patched module graph
output.set(new Uint8Array(finalModuleGraph.buffer, finalModuleGraph.byteOffset, finalModuleGraph.length), androidBunSize)

// Write new total_byte_count as u64 LE
const totalView = new DataView(output.buffer, outputSize - 8, 8)
totalView.setUint32(0, newTotalByteCount & 0xFFFFFFFF, true)
totalView.setUint32(4, Math.floor(newTotalByteCount / 0x100000000), true)

const androidOutputPath = path.join(OUTPUT_DIR, "opencode")
await Bun.write(androidOutputPath, output)
fs.chmodSync(androidOutputPath, 0o755)

// Materialize all OpenTUI file-like imports on the real Android filesystem.
// OTUI_ASSET_ROOT uses package-relative keys, so preserve those paths exactly.
const assetsRoot = path.join(OUTPUT_DIR, "opentui-assets")
fs.rmSync(assetsRoot, { recursive: true, force: true })
fs.mkdirSync(path.join(assetsRoot, "@opentui/core"), { recursive: true })
fs.copyFileSync(parserWorkerResolved, path.join(assetsRoot, "@opentui/core/parser.worker.js"))
fs.cpSync(path.join(opentuiCoreDir, "assets"), path.join(assetsRoot, "@opentui/core/assets"), { recursive: true })

const treeSitterWasm = require.resolve("web-tree-sitter/tree-sitter.wasm")
fs.mkdirSync(path.join(assetsRoot, "web-tree-sitter"), { recursive: true })
fs.copyFileSync(treeSitterWasm, path.join(assetsRoot, "web-tree-sitter/tree-sitter.wasm"))

const nativeAssetDir = path.join(assetsRoot, "@opentui/core-linux-arm64")
fs.mkdirSync(nativeAssetDir, { recursive: true })
fs.copyFileSync(ANDROID_OPENTUI, path.join(nativeAssetDir, "libopentui.so"))
// The host standalone bundle constant-folds process.arch as x64. Preserve that
// asset key as an alias, but place the Android ARM64 library behind it.
const hostNativeAssetDir = path.join(assetsRoot, "@opentui/core-linux-x64")
fs.mkdirSync(hostNativeAssetDir, { recursive: true })
fs.copyFileSync(ANDROID_OPENTUI, path.join(hostNativeAssetDir, "libopentui.so"))
console.log(`OpenTUI runtime assets: ${assetsRoot}`)

console.log(`\nAndroid standalone binary: ${androidOutputPath}`)
console.log(`Size: ${(outputSize / 1024 / 1024).toFixed(1)} MB`)

// Verify
const verifyBytes = new Uint8Array(await Bun.file(androidOutputPath).arrayBuffer())
const verifyView = new DataView(verifyBytes.buffer, verifyBytes.length - 8, 8)
const verifyTotal = verifyView.getUint32(0, true) + verifyView.getUint32(4, true) * 0x100000000
console.log(`Verification: total_byte_count=${verifyTotal}, file_size=${verifyBytes.length}, match=${verifyTotal === verifyBytes.length}`)

// Check ELF header
const elfMagic = String.fromCharCode(verifyBytes[0], verifyBytes[1], verifyBytes[2], verifyBytes[3])
console.log(`ELF magic: ${elfMagic === "\x7fELF" ? "OK" : "INVALID"}`)

console.log("\n=== Build complete! ===")
console.log(`Output: ${androidOutputPath}`)
